<?php

namespace Epsicube\Schemas\Overrides;

use Illuminate\Validation\Validator;

class CustomValidator extends Validator
{

    /**
     * Custom override to allow validating empty string
     */
    #[\Override]
   protected function presentOrRuleIsImplicit($rule, $attribute, $value): bool
    {
       if (is_string($value) && trim($value) === '') {
           return true;
       }

       return parent::presentOrRuleIsImplicit($rule, $attribute, $value); // TODO: Change the autogenerated stub
   }
}
